### PR TITLE
fix(bootstrap): minor QoL Changes

### PR DESCRIPTION
**Pull request by MaxMustermann2**
1. An indexed `delegatee` or `undelegatee` within the event will allow for easier tracking.
2. Share the `_deployVault` function between `Bootstrap` and `ClientChainGateway` by keeping it inside `BootstrapStorage`.
3. When deploying only bootstrap, use the `beaconOracle` and `beaconProxyBytecode` from pre-requisites.

### CODE REVIEW

**Comment by adu-web3** [comment]
`forge test` complains delegation tests fails and I fix the failure in new commit

**Review by adu-web3 — APPROVED** [review]
LGTM

**Comment by MaxMustermann2** [comment]
> `forge test` complains delegation tests fails and I fix the failure in new commit

thanks, I will set up a CI in a separate PR to run `forge test`

**Review by bwhour — APPROVED** [review]
it looks good.

**Pull request merged**
